### ISSUE TITLE
【建议】在此仓库里记录发源于中国或由中国人主导的开源社区

### ISSUE THREAD

**Issue by Nliver** [kaiyuanshe/K-Community#1]
是不是很酷？

**Comment by Nliver** [comment]
> 是不是很酷？

我想了想，还是得思考一下，是记录和开源社有过合作的开源社区，还是记录全国的？哈哈哈纠结了一会儿

**Comment by will-ww** [comment]
Cool~

**Comment by TechQuery** [comment]
> > 是不是很酷？
> 
> 我想了想，还是得思考一下，是记录和开源社有过合作的开源社区，还是记录全国的？哈哈哈纠结了一会儿

- 全国社区：https://test.kaiyuanshe.cn/organization
- 合作关系：https://test.kaiyuanshe.cn/organization/cooperation
